---
title: "Testing"
output: html_document
---

```{r}
set.seed(2020)
library(ggplot2)
library(tidyverse)
library(pROC)
library(broom)
source('gen_test_data.R')
source('bouldr.R')
source('rocplot.R')
# source("module 1.R")
# source("module 2.R")

dd <- gen.test.data(10,Diagnosis = c("Depression","Anxiety","ADHD","OCD"),
                          Measure = c("A","B"),
                          Informant = c("Self","Cow","Worm","Flea","Parent"))

```

New idea for package name: bouldr

TODO: test this on some real data
TODO: format as a real R package?
TODO: add more documentation
DONE: fix the direction warnings from pROC (see below)
TODO: add print and summary functions to bouldr object

```{r}
# dd$Outcome <- case_when(
#   dd$Outcome == "yes" ~ 1,
#   dd$Outcome == "no" ~ 0
# )
r <- bouldr(dat = dd,
            f = Outcome ~ Score + Informant + Diagnosis,
            test = 'delong',
            levels = c('no','yes'),
            direction = "<")
```

```{r}
rocplot(r)
```

```{r}
tests(r)
```

```{r}
rocs(r)
```


